
spring.application.name=validation-service
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=https://eureka-server-production-b348.up.railway.app/

#server.port=8989
#new code
server.port=${PORT:8989}
# Swagger OpenAPI config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

